### ISSUE TITLE
Issue with training commands

### ISSUE THREAD

**Issue by penfever** [AwesomeLemon/ENCAS#2]
I believe there is a minor typo in your readme -- the command should read --

python nat_run_many.py --config configs_nat/cifar10_reproducenat.yml

However, this is not the issue I am raising. Rather, when I run this command all of the subprocesses seem to be failing.

[{'experiment_name': '/scratch/bf996/encas/logs/cifar10_reproducenat/search_algo:nsga3!subset_selector:reference/0', 'resume': None, 'sec_obj': 'flops', 'iterations': 30, 'n_doe': 100, 'n_iter': 300, 'predictor': 'rbf_ensemble', 'data': '/scratch/bf996/datasets/cifar10/', 'dataset': 'cifar10', 'n_workers': 1, 'vld_size': 10000, 'total_size': None, 'trn_batch_size': 96, 'vld_batch_size': 150, 'n_epochs': 5, 'supernet_path': ['data/ofa/supernet_w1.0', 'data/ofa/supernet_w1.2'], 'search_algo': 'nsga3', 'subset_selector': 'reference', 'init_with_nd_front_size': 0, 'dont_check_duplicates': True, 'add_archive_to_candidates': True, 'sample_configs_to_train': True, 'random_seed': 1723, 'n_warmup_epochs': 0, 'path_logs': '/scratch/bf996/encas/logs/', 'n_surrogate_evals': 10000, 'config_msunas_path': None, 'gomea_exe': '/home/chebykin/MO_GOMEA/exes/MO_GOMEA_default_ndinit_lb_lessoutput_intsolution_dontcountcache_usepythonpath', 'alphabet': ['full_nat', 'full_nat'], 'search_space': 'reproduce_nat', 'store_checkpoint_freq': 1, 'init_lr': 0.01, 'ensemble_ss_names': ['ofa', 'ofa'], 'rbf_ensemble_size': 500, 'cutout_size': 56, 'label_smoothing': 0.0, 'if_amp': True, 'use_gradient_checkpointing': False, 'lr_schedule_type': 'cosine_nocycle', 'if_cutmix': False, 'weight_decay': 4e-05, 'if_center_crop': True, 'auto_augment': 'rand-m9-mstd0.5', 'resize_scale': 0.08, 'search_goal': 'ensemble', 'zeroeth_gpu': 0, 'gpu': 0, 'n_classes': 10, 'n_gpus': 1, 'seed_offset': 0, 'train_continuous': True, 'use_diversity_objective': False, 'n_runs': 6, 'init_with_nd_front': False, 'if_debug_run': False, 'if_create_unique_gpu_lock': False, 'if_single_gpu_mode': True, 'if_store': False, 'git_hash': '827ef869ab2e9b1c68b2e26d5ebaa0a3200675d3', 'algo_mods_all': [{'search_algo': 'nsga3', 'subset_selector': 'reference'}]}, {'experiment_name': '/scratch/bf996/encas/logs/cifar10_reproducenat/search_algo:nsga3!subset_selector:reference/1', 'resume': None, 'sec_obj': 'flops', 'iterations': 30, 'n_doe': 100, 'n_iter': 300, 'predictor': 'rbf_ensemble', 'data': '/scratch/bf996/datasets/cifar10/', 'dataset': 'cifar10', 'n_workers': 1, 'vld_size': 10000, 'total_size': None, 'trn_batch_size': 96, 'vld_batch_size': 150, 'n_epochs': 5, 'supernet_path': ['data/ofa/supernet_w1.0', 'data/ofa/supernet_w1.2'], 'search_algo': 'nsga3', 'subset_selector': 'reference', 'init_with_nd_front_size': 0, 'dont_check_duplicates': True, 'add_archive_to_candidates': True, 'sample_configs_to_train': True, 'random_seed': 1724, 'n_warmup_epochs': 0, 'path_logs': '/scratch/bf996/encas/logs/', 'n_surrogate_evals': 10000, 'config_msunas_path': None, 'gomea_exe': '/home/chebykin/MO_GOMEA/exes/MO_GOMEA_default_ndinit_lb_lessoutput_intsolution_dontcountcache_usepythonpath', 'alphabet': ['full_nat', 'full_nat'], 'search_space': 'reproduce_nat', 'store_checkpoint_freq': 1, 'init_lr': 0.01, 'ensemble_ss_names': ['ofa', 'ofa'], 'rbf_ensemble_size': 500, 'cutout_size': 56, 'label_smoothing': 0.0, 'if_amp': True, 'use_gradient_checkpointing': False, 'lr_schedule_type': 'cosine_nocycle', 'if_cutmix': False, 'weight_decay': 4e-05, 'if_center_crop': True, 'auto_augment': 'rand-m9-mstd0.5', 'resize_scale': 0.08, 'search_goal': 'ensemble', 'zeroeth_gpu': 0, 'gpu': 0, 'n_classes': 10, 'n_gpus': 1, 'seed_offset': 0, 'train_continuous': True, 'use_diversity_objective': False, 'n_runs': 6, 'init_with_nd_front': False, 'if_debug_run': False, 'if_create_unique_gpu_lock': False, 'if_single_gpu_mode': True, 'if_store': False, 'git_hash': '827ef869ab2e9b1c68b2e26d5ebaa0a3200675d3', 'algo_mods_all': [{'search_algo': 'nsga3', 'subset_selector': 'reference'}]}, {'experiment_name': '/scratch/bf996/encas/logs/cifar10_reproducenat/search_algo:nsga3!subset_selector:reference/2', 'resume': None, 'sec_obj': 'flops', 'iterations': 30, 'n_doe': 100, 'n_iter': 300, 'predictor': 'rbf_ensemble', 'data': '/scratch/bf996/datasets/cifar10/', 'dataset': 'cifar10', 'n_workers': 1, 'vld_size': 10000, 'total_size': None, 'trn_batch_size': 96, 'vld_batch_size': 150, 'n_epochs': 5, 'supernet_path': ['data/ofa/supernet_w1.0', 'data/ofa/supernet_w1.2'], 'search_algo': 'nsga3', 'subset_selector': 'reference', 'init_with_nd_front_size': 0, 'dont_check_duplicates': True, 'add_archive_to_candidates': True, 'sample_configs_to_train': True, 'random_seed': 1725, 'n_warmup_epochs': 0, 'path_logs': '/scratch/bf996/encas/logs/', 'n_surrogate_evals': 10000, 'config_msunas_path': None, 'gomea_exe': '/home/chebykin/MO_GOMEA/exes/MO_GOMEA_default_ndinit_lb_lessoutput_intsolution_dontcountcache_usepythonpath', 'alphabet': ['full_nat', 'full_nat'], 'search_space': 'reproduce_nat', 'store_checkpoint_freq': 1, 'init_lr': 0.01, 'ensemble_ss_names': ['ofa', 'ofa'], 'rbf_ensemble_size': 500, 'cutout_size': 56, 'label_smoothing': 0.0, 'if_amp': True, 'use_gradient_checkpointing': False, 'lr_schedule_type': 'cosine_nocycle', 'if_cutmix': False, 'weight_decay': 4e-05, 'if_center_crop': True, 'auto_augment': 'rand-m9-mstd0.5', 'resize_scale': 0.08, 'search_goal': 'ensemble', 'zeroeth_gpu': 0, 'gpu': 0, 'n_classes': 10, 'n_gpus': 1, 'seed_offset': 0, 'train_continuous': True, 'use_diversity_objective': False, 'n_runs': 6, 'init_with_nd_front': False, 'if_debug_run': False, 'if_create_unique_gpu_lock': False, 'if_single_gpu_mode': True, 'if_store': False, 'git_hash': '827ef869ab2e9b1c68b2e26d5ebaa0a3200675d3', 'algo_mods_all': [{'search_algo': 'nsga3', 'subset_selector': 'reference'}]}, {'experiment_name': '/scratch/bf996/encas/logs/cifar10_reproducenat/search_algo:nsga3!subset_selector:reference/3', 'resume': None, 'sec_obj': 'flops', 'iterations': 30, 'n_doe': 100, 'n_iter': 300, 'predictor': 'rbf_ensemble', 'data': '/scratch/bf996/datasets/cifar10/', 'dataset': 'cifar10', 'n_workers': 1, 'vld_size': 10000, 'total_size': None, 'trn_batch_size': 96, 'vld_batch_size': 150, 'n_epochs': 5, 'supernet_path': ['data/ofa/supernet_w1.0', 'data/ofa/supernet_w1.2'], 'search_algo': 'nsga3', 'subset_selector': 'reference', 'init_with_nd_front_size': 0, 'dont_check_duplicates': True, 'add_archive_to_candidates': True, 'sample_configs_to_train': True, 'random_seed': 1726, 'n_warmup_epochs': 0, 'path_logs': '/scratch/bf996/encas/logs/', 'n_surrogate_evals': 10000, 'config_msunas_path': None, 'gomea_exe': '/home/chebykin/MO_GOMEA/exes/MO_GOMEA_default_ndinit_lb_lessoutput_intsolution_dontcountcache_usepythonpath', 'alphabet': ['full_nat', 'full_nat'], 'search_space': 'reproduce_nat', 'store_checkpoint_freq': 1, 'init_lr': 0.01, 'ensemble_ss_names': ['ofa', 'ofa'], 'rbf_ensemble_size': 500, 'cutout_size': 56, 'label_smoothing': 0.0, 'if_amp': True, 'use_gradient_checkpointing': False, 'lr_schedule_type': 'cosine_nocycle', 'if_cutmix': False, 'weight_decay': 4e-05, 'if_center_crop': True, 'auto_augment': 'rand-m9-mstd0.5', 'resize_scale': 0.08, 'search_goal': 'ensemble', 'zeroeth_gpu': 0, 'gpu': 0, 'n_classes': 10, 'n_gpus': 1, 'seed_offset': 0, 'train_continuous': True, 'use_diversity_objective': False, 'n_runs': 6, 'init_with_nd_front': False, 'if_debug_run': False, 'if_create_unique_gpu_lock': False, 'if_single_gpu_mode': True, 'if_store': False, 'git_hash': '827ef869ab2e9b1c68b2e26d5ebaa0a3200675d3', 'algo_mods_all': [{'search_algo': 'nsga3', 'subset_selector': 'reference'}]}, {'experiment_name': '/scratch/bf996/encas/logs/cifar10_reproducenat/search_algo:nsga3!subset_selector:reference/4', 'resume': None, 'sec_obj': 'flops', 'iterations': 30, 'n_doe': 100, 'n_iter': 300, 'predictor': 'rbf_ensemble', 'data': '/scratch/bf996/datasets/cifar10/', 'dataset': 'cifar10', 'n_workers': 1, 'vld_size': 10000, 'total_size': None, 'trn_batch_size': 96, 'vld_batch_size': 150, 'n_epochs': 5, 'supernet_path': ['data/ofa/supernet_w1.0', 'data/ofa/supernet_w1.2'], 'search_algo': 'nsga3', 'subset_selector': 'reference', 'init_with_nd_front_size': 0, 'dont_check_duplicates': True, 'add_archive_to_candidates': True, 'sample_configs_to_train': True, 'random_seed': 1727, 'n_warmup_epochs': 0, 'path_logs': '/scratch/bf996/encas/logs/', 'n_surrogate_evals': 10000, 'config_msunas_path': None, 'gomea_exe': '/home/chebykin/MO_GOMEA/exes/MO_GOMEA_default_ndinit_lb_lessoutput_intsolution_dontcountcache_usepythonpath', 'alphabet': ['full_nat', 'full_nat'], 'search_space': 'reproduce_nat', 'store_checkpoint_freq': 1, 'init_lr': 0.01, 'ensemble_ss_names': ['ofa', 'ofa'], 'rbf_ensemble_size': 500, 'cutout_size': 56, 'label_smoothing': 0.0, 'if_amp': True, 'use_gradient_checkpointing': False, 'lr_schedule_type': 'cosine_nocycle', 'if_cutmix': False, 'weight_decay': 4e-05, 'if_center_crop': True, 'auto_augment': 'rand-m9-mstd0.5', 'resize_scale': 0.08, 'search_goal': 'ensemble', 'zeroeth_gpu': 0, 'gpu': 0, 'n_classes': 10, 'n_gpus': 1, 'seed_offset': 0, 'train_continuous': True, 'use_diversity_objective': False, 'n_runs': 6, 'init_with_nd_front': False, 'if_debug_run': False, 'if_create_unique_gpu_lock': False, 'if_single_gpu_mode': True, 'if_store': False, 'git_hash': '827ef869ab2e9b1c68b2e26d5ebaa0a3200675d3', 'algo_mods_all': [{'search_algo': 'nsga3', 'subset_selector': 'reference'}]}, {'experiment_name': '/scratch/bf996/encas/logs/cifar10_reproducenat/search_algo:nsga3!subset_selector:reference/5', 'resume': None, 'sec_obj': 'flops', 'iterations': 30, 'n_doe': 100, 'n_iter': 300, 'predictor': 'rbf_ensemble', 'data': '/scratch/bf996/datasets/cifar10/', 'dataset': 'cifar10', 'n_workers': 1, 'vld_size': 10000, 'total_size': None, 'trn_batch_size': 96, 'vld_batch_size': 150, 'n_epochs': 5, 'supernet_path': ['data/ofa/supernet_w1.0', 'data/ofa/supernet_w1.2'], 'search_algo': 'nsga3', 'subset_selector': 'reference', 'init_with_nd_front_size': 0, 'dont_check_duplicates': True, 'add_archive_to_candidates': True, 'sample_configs_to_train': True, 'random_seed': 1728, 'n_warmup_epochs': 0, 'path_logs': '/scratch/bf996/encas/logs/', 'n_surrogate_evals': 10000, 'config_msunas_path': None, 'gomea_exe': '/home/chebykin/MO_GOMEA/exes/MO_GOMEA_default_ndinit_lb_lessoutput_intsolution_dontcountcache_usepythonpath', 'alphabet': ['full_nat', 'full_nat'], 'search_space': 'reproduce_nat', 'store_checkpoint_freq': 1, 'init_lr': 0.01, 'ensemble_ss_names': ['ofa', 'ofa'], 'rbf_ensemble_size': 500, 'cutout_size': 56, 'label_smoothing': 0.0, 'if_amp': True, 'use_gradient_checkpointing': False, 'lr_schedule_type': 'cosine_nocycle', 'if_cutmix': False, 'weight_decay': 4e-05, 'if_center_crop': True, 'auto_augment': 'rand-m9-mstd0.5', 'resize_scale': 0.08, 'search_goal': 'ensemble', 'zeroeth_gpu': 0, 'gpu': 0, 'n_classes': 10, 'n_gpus': 1, 'seed_offset': 0, 'train_continuous': True, 'use_diversity_objective': False, 'n_runs': 6, 'init_with_nd_front': False, 'if_debug_run': False, 'if_create_unique_gpu_lock': False, 'if_single_gpu_mode': True, 'if_store': False, 'git_hash': '827ef869ab2e9b1c68b2e26d5ebaa0a3200675d3', 'algo_mods_all': [{'search_algo': 'nsga3', 'subset_selector': 'reference'}]}]
cuda =  0
Setting random seed to 1723
self.path_logs='/scratch/bf996/encas/logs/cifar10_reproducenat/search_algo:nsga3!subset_selector:reference/0'
supernet_paths=['data/ofa/supernet_w1.0', 'data/ofa/supernet_w1.2']
Color jitter: None, resize_scale: 0.08, img_size: 256
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
self.ref_dirs.shape=(100, 2)
Lock 23055866667984 acquired on /scratch/bf996/encas/logs/cifar10_reproducenat/gpu_0.lockpercent_w1_0=0.61
Traceback (most recent call last):
  File "/scratch/bf996/encas/nat_run_many.py", line 128, in execute_run
    main(algo_run_kwargs)
  File "/scratch/bf996/encas/nat.py", line 959, in main
    engine.search()
  File "/scratch/bf996/encas/nat.py", line 224, in search
    archive, first_iteration = self.create_or_restore_archive(ref_pt)
  File "/scratch/bf996/encas/nat.py", line 291, in create_or_restore_archive
    objs_evaluated = self.train_and_evaluate(arch_doe, 0)
  File "/scratch/bf996/encas/nat.py", line 405, in train_and_evaluate
    self._train(archs, it, n_epochs=n_epochs, if_warmup=if_warmup)
  File "/scratch/bf996/encas/nat.py", line 460, in _train
    future.result()
  File "/ext3/miniconda3/envs/env_encas/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/ext3/miniconda3/envs/env_encas/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by penfever** [comment]
Resolved my own issue (for future reference, the cause seems to have been that my CUDA device was not visible)

**Comment by AwesomeLemon** [comment]
Nice. I've updated the readme with the correct paths, and added a reminder to check if GPU is visible to Pytorch - thanks for pointing these issues out :)
